### ISSUE TITLE
Claming route throws "IllegalStateException"

### ISSUE THREAD

**Issue by sjrme** [cs340tabyu/CS340Summer2017#74]
java.lang.IllegalStateException: ArrayAdapter requires the resource ID to be a TextView
                      at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:401)
                      at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371)
Caused by: java.lang.ClassCastException: android.widget.ListView cannot be cast to android.widget.TextView
                      at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:388)
                      at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371) 
The server had been running a long time at this point, with several games being created/entered. In this particualar game, routes suddenly became entirely unclaimable--even when there was enough cards, it would say "Route not claimed."

**Comment by Sotaur** [comment]
Fixed
